version: '2'
services:
  django:
    build: ./
    links:
      - db
    ports:
      - 80:8000
    volumes:
      - ./:/mnt
    working_dir: /mnt
    command: python manage.py runserver 0.0.0.0:8000

  db:
    build:
      context: ./
      dockerfile: Dockerfile-db
    expose:
       - 5432
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=hello
      - POSTGRES_DB=hello
